using System.Text;

namespace RetroMultiTools.Utilities;

/// <summary>
/// Generates emulator configuration files for popular retro gaming emulators.
/// Supports RetroArch, Mesen, Snes9x, Project64, mGBA, Kega Fusion, Mednafen, Stella, FCEUX, and MAME.
/// </summary>
public static class EmulatorConfigGenerator
{
    public enum Emulator
    {
        RetroArch,
        Mesen,
        Snes9x,
        Project64,
        MGBA,
        KegaFusion,
        Mednafen,
        Stella,
        FCEUX,
        MAME
    }

    public static string GetEmulatorName(Emulator emulator) => emulator switch
    {
        Emulator.RetroArch => "RetroArch",
        Emulator.Mesen => "Mesen (NES/SNES)",
        Emulator.Snes9x => "Snes9x (SNES)",
        Emulator.Project64 => "Project64 (N64)",
        Emulator.MGBA => "mGBA (Game Boy/GBA)",
        Emulator.KegaFusion => "Kega Fusion (Sega)",
        Emulator.Mednafen => "Mednafen (Multi-system)",
        Emulator.Stella => "Stella (Atari 2600)",
        Emulator.FCEUX => "FCEUX (NES)",
        Emulator.MAME => "MAME (Arcade)",
        _ => emulator.ToString()
    };

    public static string GetConfigExtension(Emulator emulator) => emulator switch
    {
        Emulator.RetroArch => ".cfg",
        Emulator.Mesen => ".xml",
        Emulator.Snes9x => ".cfg",
        Emulator.Project64 => ".cfg",
        Emulator.MGBA => ".ini",
        Emulator.KegaFusion => ".ini",
        Emulator.Mednafen => ".cfg",
        Emulator.Stella => ".ini",
        Emulator.FCEUX => ".cfg",
        Emulator.MAME => ".ini",
        _ => ".cfg"
    };

    /// <summary>
    /// Generates a configuration file for the specified emulator.
    /// </summary>
    public static async Task GenerateAsync(
        EmulatorConfigOptions options,
        string outputPath,
        IProgress<string>? progress = null)
    {
        if (string.IsNullOrEmpty(outputPath))
            throw new ArgumentException("Output path cannot be empty.", nameof(outputPath));

        progress?.Report($"Generating {GetEmulatorName(options.Emulator)} configuration...");

        string config = options.Emulator switch
        {
            Emulator.RetroArch => GenerateRetroArch(options),
            Emulator.Mesen => GenerateMesen(options),
            Emulator.Snes9x => GenerateSnes9x(options),
            Emulator.Project64 => GenerateProject64(options),
            Emulator.MGBA => GenerateMgba(options),
            Emulator.KegaFusion => GenerateKegaFusion(options),
            Emulator.Mednafen => GenerateMednafen(options),
            Emulator.Stella => GenerateStella(options),
            Emulator.FCEUX => GenerateFceux(options),
            Emulator.MAME => GenerateMame(options),
            _ => throw new InvalidOperationException($"Unsupported emulator: {options.Emulator}")
        };

        try
        {
            string? dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir))
                Directory.CreateDirectory(dir);

            await File.WriteAllTextAsync(outputPath, config).ConfigureAwait(false);
        }
        catch
        {
            try { File.Delete(outputPath); } catch (IOException) { } catch (UnauthorizedAccessException) { }
            throw;
        }

        progress?.Report("Done.");
    }

    private static string GenerateRetroArch(EmulatorConfigOptions options)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# RetroArch Configuration");
        sb.AppendLine($"# Generated by RetroMultiTools on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        // Video settings
        sb.AppendLine("# Video");
        sb.AppendLine($"video_fullscreen = \"{options.Fullscreen.ToString().ToLowerInvariant()}\"");
        sb.AppendLine($"video_smooth = \"{options.SmoothVideo.ToString().ToLowerInvariant()}\"");
        sb.AppendLine($"video_shader_enable = \"{options.EnableShaders.ToString().ToLowerInvariant()}\"");
        sb.AppendLine($"video_vsync = \"{options.VSync.ToString().ToLowerInvariant()}\"");
        sb.AppendLine($"video_driver = \"{options.VideoDriver}\"");
        sb.AppendLine($"video_threaded = \"{options.ThreadedVideo.ToString().ToLowerInvariant()}\"");
        sb.AppendLine($"video_scale_integer = \"{options.IntegerScaling.ToString().ToLowerInvariant()}\"");
        if (!options.Fullscreen)
            sb.AppendLine("video_scale = \"3\""); // 3× native resolution for windowed mode
        sb.AppendLine("video_msg_pos_x = \"0.05\"");
        sb.AppendLine("video_msg_pos_y = \"0.05\"");

        sb.AppendLine();

        // Audio settings
        sb.AppendLine("# Audio");
        sb.AppendLine($"audio_enable = \"true\"");
        if (options.AudioDriver != "auto")
            sb.AppendLine($"audio_driver = \"{options.AudioDriver}\"");
        sb.AppendLine($"audio_sync = \"{options.AudioSyncRetroArch.ToString().ToLowerInvariant()}\"");
        // RetroArch uses a -80 to 0 dB scale; convert 0-100% linear volume to dB
        double retroArchVolumeDb = (options.AudioVolume * 80.0 / 100.0) - 80.0;
        sb.AppendLine($"audio_volume = \"{retroArchVolumeDb:F1}\"");
        sb.AppendLine("audio_latency = \"64\"");
        sb.AppendLine();

        // Input settings
        sb.AppendLine("# Input");
        if (options.InputDriver != "auto")
            sb.AppendLine($"input_driver = \"{options.InputDriver}\"");
        sb.AppendLine($"input_autodetect_enable = \"true\"");
        sb.AppendLine("input_menu_toggle_gamepad_combo = \"2\"");
        sb.AppendLine();

        // Paths
        sb.AppendLine("# Paths");
        if (!string.IsNullOrEmpty(options.RomDirectory))
        {
            string romDir = NormalizePath(options.RomDirectory);
            sb.AppendLine($"rgui_browser_directory = \"{romDir}\"");
            sb.AppendLine($"content_directory = \"{romDir}\"");
        }

        if (!string.IsNullOrEmpty(options.SaveDirectory))
            sb.AppendLine($"savefile_directory = \"{NormalizePath(options.SaveDirectory)}\"");

        if (!string.IsNullOrEmpty(options.StateDirectory))
            sb.AppendLine($"savestate_directory = \"{NormalizePath(options.StateDirectory)}\"");

        if (!string.IsNullOrEmpty(options.ScreenshotDirectory))
            sb.AppendLine($"screenshot_directory = \"{NormalizePath(options.ScreenshotDirectory)}\"");

        sb.AppendLine();

        // General / core settings
        sb.AppendLine("# General");
        sb.AppendLine($"rewind_enable = \"{options.EnableRewind.ToString().ToLowerInvariant()}\"");
        if (options.EnableRewind)
            sb.AppendLine("rewind_granularity = \"2\"");
        sb.AppendLine($"savestate_auto_save = \"{options.AutoSaveState.ToString().ToLowerInvariant()}\"");
        sb.AppendLine($"savestate_auto_load = \"{options.AutoSaveState.ToString().ToLowerInvariant()}\"");
        sb.AppendLine($"menu_driver = \"{options.MenuDriver}\"");
        sb.AppendLine($"fps_show = \"{options.ShowFPS.ToString().ToLowerInvariant()}\"");
        sb.AppendLine($"notification_show_when_menu_is_alive = \"{options.EnableNotifications.ToString().ToLowerInvariant()}\"");
        sb.AppendLine($"cheats_enable = \"{options.EnableCheats.ToString().ToLowerInvariant()}\"");
        sb.AppendLine($"config_save_on_exit = \"{options.ConfigSaveOnExit.ToString().ToLowerInvariant()}\"");
        sb.AppendLine($"pause_nonactive = \"{options.PauseOnUnfocus.ToString().ToLowerInvariant()}\"");

        // Latency reduction
        sb.AppendLine();
        sb.AppendLine("# Latency");
        sb.AppendLine($"run_ahead_enabled = \"{(options.RunAheadFrames > 0).ToString().ToLowerInvariant()}\"");
        sb.AppendLine($"run_ahead_frames = \"{options.RunAheadFrames}\"");

        return sb.ToString();
    }

    private static string GenerateMesen(EmulatorConfigOptions options)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
        sb.AppendLine("<!-- Mesen Configuration -->");
        sb.AppendLine($"<!-- Generated by RetroMultiTools on {DateTime.Now:yyyy-MM-dd HH:mm:ss} -->");
        sb.AppendLine("<Settings>");
        sb.AppendLine("  <Video>");
        sb.AppendLine($"    <FullscreenMode>{(options.Fullscreen ? "true" : "false")}</FullscreenMode>");
        sb.AppendLine($"    <UseBilinearInterpolation>{(options.SmoothVideo ? "true" : "false")}</UseBilinearInterpolation>");
        sb.AppendLine($"    <IntegerScaling>{(options.IntegerScaling ? "true" : "false")}</IntegerScaling>");
        sb.AppendLine($"    <VerticalSync>{(options.VSync ? "true" : "false")}</VerticalSync>");
        sb.AppendLine($"    <ShowFPS>{(options.ShowFPS ? "true" : "false")}</ShowFPS>");
        sb.AppendLine("  </Video>");
        sb.AppendLine("  <Audio>");
        sb.AppendLine("    <EnableAudio>true</EnableAudio>");
        sb.AppendLine($"    <MasterVolume>{options.AudioVolume}</MasterVolume>");
        sb.AppendLine("  </Audio>");
        sb.AppendLine("  <Emulation>");
        sb.AppendLine($"    <Region>{EscapeXml(options.Region)}</Region>");
        sb.AppendLine($"    <RemoveSpriteLimit>{(options.RemoveSpriteLimit ? "true" : "false")}</RemoveSpriteLimit>");
        sb.AppendLine($"    <Overclock>{(options.Overclock ? "true" : "false")}</Overclock>");
        sb.AppendLine($"    <EnableCheats>{(options.EnableCheats ? "true" : "false")}</EnableCheats>");
        sb.AppendLine("  </Emulation>");
        sb.AppendLine("  <Preferences>");

        if (!string.IsNullOrEmpty(options.RomDirectory))
            sb.AppendLine($"    <RomFolder>{EscapeXml(options.RomDirectory)}</RomFolder>");

        if (!string.IsNullOrEmpty(options.SaveDirectory))
            sb.AppendLine($"    <SaveFolder>{EscapeXml(options.SaveDirectory)}</SaveFolder>");

        if (!string.IsNullOrEmpty(options.StateDirectory))
            sb.AppendLine($"    <SaveStateFolder>{EscapeXml(options.StateDirectory)}</SaveStateFolder>");

        if (!string.IsNullOrEmpty(options.ScreenshotDirectory))
            sb.AppendLine($"    <ScreenshotFolder>{EscapeXml(options.ScreenshotDirectory)}</ScreenshotFolder>");

        sb.AppendLine($"    <RewindEnabled>{(options.EnableRewind ? "true" : "false")}</RewindEnabled>");
        sb.AppendLine("  </Preferences>");
        sb.AppendLine("</Settings>");

        return sb.ToString();
    }

    private static string GenerateSnes9x(EmulatorConfigOptions options)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# Snes9x Configuration");
        sb.AppendLine($"# Generated by RetroMultiTools on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        sb.AppendLine("[Display]");
        sb.AppendLine($"FullScreen={options.Fullscreen.ToString().ToUpperInvariant()}");
        sb.AppendLine($"Bilinear={options.SmoothVideo.ToString().ToUpperInvariant()}");
        sb.AppendLine($"VSync={options.VSync.ToString().ToUpperInvariant()}");
        sb.AppendLine($"IntegerScaling={options.IntegerScaling.ToString().ToUpperInvariant()}");
        sb.AppendLine($"ShowFPS={options.ShowFPS.ToString().ToUpperInvariant()}");
        sb.AppendLine();

        sb.AppendLine("[Sound]");
        sb.AppendLine("Enabled=TRUE");
        sb.AppendLine("Sync=TRUE");
        sb.AppendLine($"Volume={options.AudioVolume}");
        sb.AppendLine($"DynamicRateControl={options.DynamicRateControl.ToString().ToUpperInvariant()}");
        sb.AppendLine();

        sb.AppendLine("[Emulation]");
        sb.AppendLine($"Region={options.Region}");
        sb.AppendLine($"TurboSpeed={options.TurboSpeed}");
        sb.AppendLine($"SuperFXOverclock={options.SuperFXOverclock.ToString().ToUpperInvariant()}");
        sb.AppendLine($"BlockInvalidVRAMAccess={options.BlockInvalidVram.ToString().ToUpperInvariant()}");
        sb.AppendLine($"EnableCheats={options.EnableCheats.ToString().ToUpperInvariant()}");
        sb.AppendLine();

        sb.AppendLine("[Paths]");
        if (!string.IsNullOrEmpty(options.RomDirectory))
            sb.AppendLine($"RomDir={options.RomDirectory}");
        if (!string.IsNullOrEmpty(options.SaveDirectory))
            sb.AppendLine($"SRAMDir={options.SaveDirectory}");
        if (!string.IsNullOrEmpty(options.StateDirectory))
            sb.AppendLine($"SaveStateDir={options.StateDirectory}");

        return sb.ToString();
    }

    private static string GenerateProject64(EmulatorConfigOptions options)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# Project64 Configuration");
        sb.AppendLine($"# Generated by RetroMultiTools on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        sb.AppendLine("[Settings]");
        sb.AppendLine($"FullScreen={BoolToInt(options.Fullscreen)}");
        sb.AppendLine();

        sb.AppendLine("[Display]");
        sb.AppendLine($"AnisotropicFiltering={BoolToInt(options.SmoothVideo)}");
        sb.AppendLine($"ShowSpeed={BoolToInt(options.DisplaySpeed)}");
        sb.AppendLine();

        sb.AppendLine("[Audio]");
        sb.AppendLine($"Volume={options.AudioVolume}");
        sb.AppendLine();

        sb.AppendLine("[CPU]");
        sb.AppendLine($"Core={options.CpuCore}");
        sb.AppendLine($"CounterFactor={options.CounterFactor}");
        sb.AppendLine();

        sb.AppendLine("[Options]");
        sb.AppendLine($"AutoSaveState={BoolToInt(options.AutoSaveState)}");
        sb.AppendLine($"EnableCheats={BoolToInt(options.EnableCheats)}");
        sb.AppendLine();

        sb.AppendLine("[Directories]");
        if (!string.IsNullOrEmpty(options.RomDirectory))
            sb.AppendLine($"RomDir={options.RomDirectory}");
        if (!string.IsNullOrEmpty(options.SaveDirectory))
            sb.AppendLine($"SaveDir={options.SaveDirectory}");
        if (!string.IsNullOrEmpty(options.StateDirectory))
            sb.AppendLine($"InstantSaveDir={options.StateDirectory}");

        return sb.ToString();
    }

    private static string GenerateMgba(EmulatorConfigOptions options)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"; mGBA Configuration");
        sb.AppendLine($"; Generated by RetroMultiTools on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        sb.AppendLine("[display]");
        sb.AppendLine($"fullscreen={BoolToInt(options.Fullscreen)}");
        sb.AppendLine($"filter={BoolToInt(options.SmoothVideo)}");
        sb.AppendLine($"lockIntegerScaling={BoolToInt(options.IntegerScaling)}");
        sb.AppendLine();

        sb.AppendLine("[audio]");
        sb.AppendLine("mute=0");
        sb.AppendLine($"audioSync={BoolToInt(options.AudioSync)}");
        sb.AppendLine($"volume={options.AudioVolume}");
        sb.AppendLine();

        sb.AppendLine("[paths]");
        if (!string.IsNullOrEmpty(options.RomDirectory))
            sb.AppendLine($"roms={options.RomDirectory}");
        if (!string.IsNullOrEmpty(options.SaveDirectory))
            sb.AppendLine($"saves={options.SaveDirectory}");
        if (!string.IsNullOrEmpty(options.StateDirectory))
            sb.AppendLine($"states={options.StateDirectory}");
        if (!string.IsNullOrEmpty(options.ScreenshotDirectory))
            sb.AppendLine($"screenshots={options.ScreenshotDirectory}");

        sb.AppendLine();
        sb.AppendLine("[gb]");
        sb.AppendLine($"useBios={BoolToInt(options.UseBios)}");
        sb.AppendLine();
        sb.AppendLine("[gba]");
        sb.AppendLine($"useBios={BoolToInt(options.UseBios)}");
        sb.AppendLine();
        sb.AppendLine("[emulation]");
        sb.AppendLine($"fastForwardSpeed={options.FastForwardSpeed}");
        sb.AppendLine($"cheats={BoolToInt(options.EnableCheats)}");
        sb.AppendLine($"frameskip={options.FrameSkip}");
        sb.AppendLine($"allowOpposingDirections={BoolToInt(options.AllowOpposingDirections)}");

        return sb.ToString();
    }

    private static string GenerateKegaFusion(EmulatorConfigOptions options)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"; Kega Fusion Configuration");
        sb.AppendLine($"; Generated by RetroMultiTools on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        sb.AppendLine("[General]");
        sb.AppendLine($"FullScreen={BoolToInt(options.Fullscreen)}");
        sb.AppendLine($"VSync={BoolToInt(options.VSync)}");
        sb.AppendLine($"Filtered={BoolToInt(options.SmoothVideo)}");
        sb.AppendLine($"Region={options.Region}");
        sb.AppendLine($"PerfectSync={BoolToInt(options.PerfectSync)}");
        sb.AppendLine();

        sb.AppendLine("[Audio]");
        sb.AppendLine($"Volume={options.AudioVolume}");
        sb.AppendLine();

        sb.AppendLine("[Options]");
        sb.AppendLine($"SRAMAutoSave={BoolToInt(options.SramAutoSave)}");
        sb.AppendLine($"EnableCheats={BoolToInt(options.EnableCheats)}");
        sb.AppendLine();

        sb.AppendLine("[Paths]");
        if (!string.IsNullOrEmpty(options.RomDirectory))
            sb.AppendLine($"ROMs={options.RomDirectory}");
        if (!string.IsNullOrEmpty(options.SaveDirectory))
            sb.AppendLine($"SRAM={options.SaveDirectory}");

        return sb.ToString();
    }

    private static string GenerateMednafen(EmulatorConfigOptions options)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"; Mednafen Configuration");
        sb.AppendLine($"; Generated by RetroMultiTools on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"; Multi-system emulator (PC Engine, Lynx, Neo Geo Pocket, SMS, Game Gear, etc.)");
        sb.AppendLine();

        // Video settings
        sb.AppendLine("; Video");
        sb.AppendLine($"video.driver {options.MednafenVideoDriver}");
        sb.AppendLine($"video.fs {BoolToInt(options.Fullscreen)}");
        sb.AppendLine($"video.glvsync {BoolToInt(options.VSync)}");
        if (options.IntegerScaling)
            sb.AppendLine("video.disable_composition 1");
        sb.AppendLine();

        // Audio settings
        sb.AppendLine("; Audio");
        sb.AppendLine($"sound.volume {options.AudioVolume}");
        sb.AppendLine("sound.rate 48000");
        sb.AppendLine($"sound.buffer_time {options.SoundBufferSize}");
        sb.AppendLine();

        // OSD / display
        sb.AppendLine("; OSD");
        // state_display_time: how long save-state OSD messages are shown (seconds)
        sb.AppendLine($"osd.state_display_time {(options.ShowFPS ? "5" : "2")}");
        // fps.autoenable: auto-show FPS counter
        sb.AppendLine($"fps.autoenable {BoolToInt(options.ShowFPS)}");
        sb.AppendLine();

        // Cheats
        sb.AppendLine("; Cheats");
        sb.AppendLine($"cheats {BoolToInt(options.EnableCheats)}");
        sb.AppendLine();

        // CD image memory cache
        sb.AppendLine("; CD-ROM");
        sb.AppendLine($"cd.image_memcache {BoolToInt(options.CdImageMemoryCache)}");
        sb.AppendLine();

        // System-specific video settings
        sb.AppendLine("; PC Engine / TurboGrafx-16");
        sb.AppendLine($"pce.videoip {BoolToInt(options.SmoothVideo)}");
        if (options.EnableShaders)
            sb.AppendLine("pce.shader goat");
        sb.AppendLine();

        sb.AppendLine("; Atari Lynx");
        sb.AppendLine($"lynx.videoip {BoolToInt(options.SmoothVideo)}");
        if (options.EnableShaders)
            sb.AppendLine("lynx.shader goat");
        sb.AppendLine();

        sb.AppendLine("; Neo Geo Pocket");
        sb.AppendLine($"ngp.videoip {BoolToInt(options.SmoothVideo)}");
        if (options.EnableShaders)
            sb.AppendLine("ngp.shader goat");
        sb.AppendLine();

        sb.AppendLine("; Sega Master System");
        sb.AppendLine($"sms.videoip {BoolToInt(options.SmoothVideo)}");
        if (options.EnableShaders)
            sb.AppendLine("sms.shader goat");
        sb.AppendLine();

        sb.AppendLine("; Game Gear");
        sb.AppendLine($"gg.videoip {BoolToInt(options.SmoothVideo)}");
        if (options.EnableShaders)
            sb.AppendLine("gg.shader goat");
        sb.AppendLine();

        sb.AppendLine("; Virtual Boy");
        sb.AppendLine($"vb.videoip {BoolToInt(options.SmoothVideo)}");
        if (options.EnableShaders)
            sb.AppendLine("vb.shader goat");
        sb.AppendLine("vb.anaglyph.preset red_blue");
        sb.AppendLine();

        sb.AppendLine("; NES");
        sb.AppendLine($"nes.videoip {BoolToInt(options.SmoothVideo)}");
        if (options.EnableShaders)
            sb.AppendLine("nes.shader goat");
        sb.AppendLine();

        sb.AppendLine("; SNES");
        sb.AppendLine($"snes.videoip {BoolToInt(options.SmoothVideo)}");
        if (options.EnableShaders)
            sb.AppendLine("snes.shader goat");
        sb.AppendLine();

        sb.AppendLine("; Game Boy / Game Boy Advance");
        sb.AppendLine($"gb.videoip {BoolToInt(options.SmoothVideo)}");
        if (options.EnableShaders)
            sb.AppendLine("gb.shader goat");
        sb.AppendLine($"gba.videoip {BoolToInt(options.SmoothVideo)}");
        if (options.EnableShaders)
            sb.AppendLine("gba.shader goat");
        sb.AppendLine();

        sb.AppendLine("; Mega Drive / Genesis");
        sb.AppendLine($"md.videoip {BoolToInt(options.SmoothVideo)}");
        if (options.EnableShaders)
            sb.AppendLine("md.shader goat");
        sb.AppendLine();

        // Paths
        if (!string.IsNullOrEmpty(options.RomDirectory) ||
            !string.IsNullOrEmpty(options.SaveDirectory) ||
            !string.IsNullOrEmpty(options.StateDirectory) ||
            !string.IsNullOrEmpty(options.ScreenshotDirectory))
        {
            sb.AppendLine("; Paths");
            if (!string.IsNullOrEmpty(options.SaveDirectory))
            {
                sb.AppendLine($"filesys.path_sav {NormalizePath(options.SaveDirectory)}");
                sb.AppendLine($"filesys.path_savbackup {NormalizePath(options.SaveDirectory)}/backup");
            }
            if (!string.IsNullOrEmpty(options.StateDirectory))
                sb.AppendLine($"filesys.path_state {NormalizePath(options.StateDirectory)}");
            if (!string.IsNullOrEmpty(options.ScreenshotDirectory))
                sb.AppendLine($"filesys.path_snap {NormalizePath(options.ScreenshotDirectory)}");
        }

        return sb.ToString();
    }

    private static string GenerateStella(EmulatorConfigOptions options)
    {
        var sb = new StringBuilder();
        sb.AppendLine("; Stella Configuration");
        sb.AppendLine($"; Generated by RetroMultiTools on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        sb.AppendLine("[Video]");
        sb.AppendLine($"fullscreen = {options.Fullscreen.ToString().ToLowerInvariant()}");
        sb.AppendLine($"vsync = {options.VSync.ToString().ToLowerInvariant()}");
        sb.AppendLine($"tv.filter = {(options.SmoothVideo ? "1" : "0")}");
        sb.AppendLine($"tv.scanlines = {options.TvEffects}");
        sb.AppendLine($"palette = {options.Palette}");
        sb.AppendLine($"phosphor = {(options.Phosphor ? "always" : "byrom")}");
        if (options.IntegerScaling)
            sb.AppendLine("tia.inter = true");
        sb.AppendLine($"showinfo = {(options.ShowFPS ? "true" : "false")}");
        sb.AppendLine();

        sb.AppendLine("[Audio]");
        sb.AppendLine("sound = true");
        sb.AppendLine($"volume = {options.AudioVolume}");
        sb.AppendLine();

        sb.AppendLine("[Input]");
        sb.AppendLine($"cheat = {(options.EnableCheats ? "true" : "false")}");
        sb.AppendLine();

        sb.AppendLine("[Paths]");
        if (!string.IsNullOrEmpty(options.RomDirectory))
            sb.AppendLine($"romdir = {options.RomDirectory}");
        if (!string.IsNullOrEmpty(options.ScreenshotDirectory))
            sb.AppendLine($"snapshotdir = {options.ScreenshotDirectory}");

        return sb.ToString();
    }

    private static string GenerateFceux(EmulatorConfigOptions options)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# FCEUX Configuration");
        sb.AppendLine($"# Generated by RetroMultiTools on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        sb.AppendLine($"SDL.Fullscreen = {BoolToInt(options.Fullscreen)}");
        sb.AppendLine("SDL.Sound = 1");
        sb.AppendLine($"SDL.Sound.Volume = {options.AudioVolume}");
        sb.AppendLine($"SDL.Sound.Quality = {options.SoundQuality}");
        sb.AppendLine("SDL.VideoDriver = 0");
        sb.AppendLine($"SDL.ShowFPS = {BoolToInt(options.ShowFPS)}");
        sb.AppendLine($"SDL.AutoSaveState = {BoolToInt(options.AutoSaveState)}");
        sb.AppendLine();

        sb.AppendLine($"SDL.Region = {options.Region}");
        sb.AppendLine($"SDL.RemoveSpriteLimit = {BoolToInt(options.RemoveSpriteLimit)}");
        sb.AppendLine($"SDL.NewPPU = {BoolToInt(options.NewPPU)}");
        sb.AppendLine($"SDL.EnableCheats = {BoolToInt(options.EnableCheats)}");
        sb.AppendLine($"SDL.GameGenie = {BoolToInt(options.GameGenie)}");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(options.RomDirectory))
            sb.AppendLine($"SDL.LastOpenFile = {options.RomDirectory}");

        return sb.ToString();
    }

    private static string GenerateMame(EmulatorConfigOptions options)
    {
        var sb = new StringBuilder(2048);
        sb.AppendLine("#");
        sb.AppendLine("# MAME Configuration");
        sb.AppendLine($"# Generated by RetroMultiTools on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("#");
        sb.AppendLine();

        // Core path options
        sb.AppendLine("#");
        sb.AppendLine("# CORE PATH OPTIONS");
        sb.AppendLine("#");
        if (!string.IsNullOrEmpty(options.RomDirectory))
            sb.AppendLine($"rompath                   {options.RomDirectory}");
        sb.AppendLine("hashpath                  hash");
        sb.AppendLine("samplepath                samples");
        sb.AppendLine("artpath                   artwork");
        sb.AppendLine("ctrlrpath                 ctrlr");
        sb.AppendLine("inipath                   .;ini;ini/presets");
        sb.AppendLine("fontpath                  .");
        sb.AppendLine("cheatpath                 cheat");
        sb.AppendLine("crosshairpath             crosshair");
        sb.AppendLine("pluginspath               plugins");
        sb.AppendLine("languagepath              language");
        sb.AppendLine();

        // Core output directory options
        sb.AppendLine("#");
        sb.AppendLine("# CORE OUTPUT DIRECTORY OPTIONS");
        sb.AppendLine("#");
        sb.AppendLine("cfg_directory             cfg");
        if (!string.IsNullOrEmpty(options.SaveDirectory))
            sb.AppendLine($"nvram_directory           {options.SaveDirectory}");
        else
            sb.AppendLine("nvram_directory           nvram");
        sb.AppendLine("input_directory           inp");
        if (!string.IsNullOrEmpty(options.StateDirectory))
            sb.AppendLine($"state_directory           {options.StateDirectory}");
        else
            sb.AppendLine("state_directory           sta");
        if (!string.IsNullOrEmpty(options.ScreenshotDirectory))
            sb.AppendLine($"snapshot_directory        {options.ScreenshotDirectory}");
        else
            sb.AppendLine("snapshot_directory        snap");
        sb.AppendLine("diff_directory            diff");
        sb.AppendLine("comment_directory         comments");
        sb.AppendLine();

        // Core performance options
        sb.AppendLine("#");
        sb.AppendLine("# CORE PERFORMANCE OPTIONS");
        sb.AppendLine("#");
        sb.AppendLine("autoframeskip             0");
        sb.AppendLine("frameskip                 0");
        sb.AppendLine("throttle                  1");
        sb.AppendLine("sleep                     1");
        sb.AppendLine("speed                     1.0");
        sb.AppendLine("refreshspeed              0");
        sb.AppendLine("lowlatency                0");
        sb.AppendLine();

        // Core rotation options
        sb.AppendLine("#");
        sb.AppendLine("# CORE ROTATION OPTIONS");
        sb.AppendLine("#");
        sb.AppendLine("rotate                    1");
        sb.AppendLine("ror                       0");
        sb.AppendLine("rol                       0");
        sb.AppendLine("autoror                   0");
        sb.AppendLine("autorol                   0");
        sb.AppendLine("flipx                     0");
        sb.AppendLine("flipy                     0");
        sb.AppendLine();

        // Core video options
        sb.AppendLine("#");
        sb.AppendLine("# CORE VIDEO OPTIONS");
        sb.AppendLine("#");
        sb.AppendLine("video                     auto");
        sb.AppendLine("numscreens                1");
        sb.AppendLine($"window                    {(options.Fullscreen ? "0" : "1")}");
        sb.AppendLine("maximize                  1");
        sb.AppendLine($"waitvsync                 {BoolToInt(options.VSync)}");
        sb.AppendLine("syncrefresh               0");
        if (options.IntegerScaling)
            sb.AppendLine("unevenstretch             0");
        if (options.SmoothVideo)
            sb.AppendLine("filter                    1");
        else
            sb.AppendLine("filter                    0");
        sb.AppendLine();

        // Core sound options
        sb.AppendLine("#");
        sb.AppendLine("# CORE SOUND OPTIONS");
        sb.AppendLine("#");
        sb.AppendLine("sound                     1");
        sb.AppendLine("samplerate                48000");
        sb.AppendLine("samples                   1");
        // MAME uses a -32 to 0 dB scale; convert 0-100% linear volume to dB
        int mameVolumeDb = (options.AudioVolume * 32 / 100) - 32;
        sb.AppendLine($"volume                    {mameVolumeDb}");
        sb.AppendLine();

        // Core input options
        sb.AppendLine("#");
        sb.AppendLine("# CORE INPUT OPTIONS");
        sb.AppendLine("#");
        sb.AppendLine("coin_lockout              1");
        sb.AppendLine("mouse                     0");
        sb.AppendLine("joystick                  1");
        sb.AppendLine("lightgun                  0");
        sb.AppendLine("multikeyboard             0");
        sb.AppendLine("multimouse                0");
        sb.AppendLine("steadykey                 0");
        sb.AppendLine("offscreen_reload          0");
        sb.AppendLine("natural                   0");
        sb.AppendLine();

        // Core state/playback options
        sb.AppendLine("#");
        sb.AppendLine("# CORE STATE/PLAYBACK OPTIONS");
        sb.AppendLine("#");
        sb.AppendLine($"autosave                  {BoolToInt(options.AutoSaveState)}");
        sb.AppendLine($"rewind                    {BoolToInt(options.EnableRewind)}");
        sb.AppendLine("rewind_capacity           100");
        sb.AppendLine();

        // OSD options
        sb.AppendLine("#");
        sb.AppendLine("# OSD OPTIONS");
        sb.AppendLine("#");
        if (options.EnableShaders)
        {
            sb.AppendLine("gl_glsl                   1");
            sb.AppendLine("gl_glsl_filter            1");
        }
        sb.AppendLine($"skip_gameinfo             {BoolToInt(options.SkipGameInfo)}");
        sb.AppendLine($"skip_warnings             {BoolToInt(options.SkipWarnings)}");
        sb.AppendLine($"cheat                     {BoolToInt(options.EnableCheats)}");

        return sb.ToString();
    }

    private static string BoolToInt(bool value) => value ? "1" : "0";

    /// <summary>
    /// Normalizes a file path for cross-platform emulator configs by replacing
    /// backslashes with forward slashes.
    /// </summary>
    private static string NormalizePath(string path) => path.Replace("\\", "/");

    private static string EscapeXml(string value) =>
        value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;")
             .Replace("\"", "&quot;").Replace("'", "&apos;");
}

public class EmulatorConfigOptions
{
    public EmulatorConfigGenerator.Emulator Emulator { get; set; }
    public string RomDirectory { get; set; } = string.Empty;
    public string SaveDirectory { get; set; } = string.Empty;
    public string StateDirectory { get; set; } = string.Empty;
    public string ScreenshotDirectory { get; set; } = string.Empty;
    public bool Fullscreen { get; set; }
    public bool SmoothVideo { get; set; } = true;
    public bool IntegerScaling { get; set; } = true;
    public bool EnableShaders { get; set; }
    public bool EnableRewind { get; set; }

    // Common options
    public bool VSync { get; set; } = true;
    public int AudioVolume { get; set; } = 100;
    public bool ShowFPS { get; set; }
    public bool AutoSaveState { get; set; }

    // RetroArch-specific
    public string VideoDriver { get; set; } = "gl";
    public string MenuDriver { get; set; } = "ozone";
    public string AudioDriver { get; set; } = "auto";
    public string InputDriver { get; set; } = "auto";
    public int RunAheadFrames { get; set; }
    public bool ThreadedVideo { get; set; }
    public bool EnableNotifications { get; set; } = true;
    public bool EnableCheats { get; set; }
    public bool AudioSyncRetroArch { get; set; } = true;
    public bool ConfigSaveOnExit { get; set; } = true;
    public bool PauseOnUnfocus { get; set; }

    // Region (Mesen, FCEUX, Snes9x, Kega Fusion)
    public string Region { get; set; } = "Auto";

    // NES-specific (Mesen, FCEUX)
    public bool RemoveSpriteLimit { get; set; }
    public bool Overclock { get; set; }

    // Snes9x-specific
    public int TurboSpeed { get; set; } = 2;
    public bool SuperFXOverclock { get; set; }
    public bool BlockInvalidVram { get; set; } = true;
    public bool DynamicRateControl { get; set; }

    // Project64-specific
    public string CpuCore { get; set; } = "Recompiler";
    public int CounterFactor { get; set; } = 2;
    public bool DisplaySpeed { get; set; }

    // mGBA-specific
    public bool AudioSync { get; set; } = true;
    public bool UseBios { get; set; } = true;
    public int FastForwardSpeed { get; set; } = 4;
    public int FrameSkip { get; set; }
    public bool AllowOpposingDirections { get; set; }

    // Stella-specific
    public string Palette { get; set; } = "standard";
    public bool Phosphor { get; set; }
    public int TvEffects { get; set; }

    // MAME-specific
    public bool SkipGameInfo { get; set; }
    public bool SkipWarnings { get; set; }

    // Mednafen-specific
    public bool CdImageMemoryCache { get; set; }
    public int SoundBufferSize { get; set; } = 32;
    public string MednafenVideoDriver { get; set; } = "opengl";

    // Kega Fusion-specific
    public bool PerfectSync { get; set; }
    public bool SramAutoSave { get; set; } = true;

    // FCEUX-specific
    public bool NewPPU { get; set; }
    public int SoundQuality { get; set; } = 1;
    public bool GameGenie { get; set; }
}
